### ISSUE TITLE
How to deploy this locally?

### ISSUE THREAD

**Issue by Paul-Hoo** [as-ideas/crowdsource#58]
Hello, I'm a newbie, just want to deploy this locally and see how it looks like, anyone could tell what steps should be done, and before that, what are pre-requirements should be installed into the environment? THX.

**Comment by wThomas84** [comment]
Hi,

basic pre requirements are 
 * Java SDK version 8
 * Maven

The application requires a MongoDb database. In the steps below you see how you can start one that runs in memory and basically ships with the code. So let's start;

1. Checkout this repository from github.
2. Build the project by running the following within a terminal, being located in the project path:
`mvn clean install -DskipTests`
(We skip the tests here, due to otherwise all tests would be executed, which takes quite a while)
3. Start an in memory mongoDb instance
   
   .. by opening a second terminal, being located in the project directory, and running:

   `mvn com.github.joelittlejohn.embedmongo:embedmongo-maven-plugin:0.1.12:start -Dembedmongo.wait -Dmongodb.test.port=27017`
   Note, that this terminal must stay open as long as you need the database. 
4. Start the actual application in your 1st terminal by:

   `java -jar -Dde.asideas.crowdsource.db.hosts=127.0.0.1 crowdsource-example/target/crowdsource-example.jar`
5. Open the web application in your browser by navigating to:
   `http://localhost:8080`

Regards,
Tom

**Comment by Paul-Hoo** [comment]
Thank you Tom, for the quick response. I'll go through these steps carefully. And mark this close as soon as it's done without issues.

**Comment by Paul-Hoo** [comment]
Hi Tom, recently I picked back this project I wanted to deploy a long time ago.
But I got issue when this step `mvn clean install -DskipTests`.
It looks like the Got endDate is not equal to the Expected endDate. What to do to correct this issue then? Thank you.

> The error shows during building the crowdsource-frontend, and the full log is as follows - 
```
[root@bogon crowdsource]#  mvn clean install -DskipTests -e
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for de.asideas.crowdsource:crowdsource-frontend:jar:1.3-SNAPSHOT
[WARNING] The expression ${build.outputDirectory} is deprecated. Please use ${project.build.outputDirectory} instead.
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] crowdsource-parent
[INFO] crowdsource-frontend
[INFO] crowdsource-core
[INFO] crowdsource-example
[INFO] crowdsource-integrationtests
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building crowdsource-parent 1.3-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ crowdsource-parent ---
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ crowdsource-parent ---
[INFO] Installing /crowdsource/pom.xml to /root/.m2/repository/de/asideas/crowdsource/crowdsource-parent/1.3-SNAPSHOT/crowdsource-parent-1.3-SNAPSHOT.pom
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building crowdsource-frontend 1.3-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ crowdsource-frontend ---
[INFO] Deleting /crowdsource/crowdsource-frontend/target
[INFO] 
[INFO] --- maven-resources-plugin:2.7:copy-resources (copy-frontend-sources) @ crowdsource-frontend ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 30 resources
[INFO] Copying 1 resource
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.23:install-node-and-npm (install node and npm) @ crowdsource-frontend ---
[INFO] Node v0.10.18 is already installed.
[INFO] Found NPM version 1.3.8
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.23:npm (npm install) @ crowdsource-frontend ---
[INFO] Running 'npm install --color=false' in /crowdsource/crowdsource-frontend
[ERROR] npm WARN cannot run in wd @ bower install --allow-root --config.interactive=false (wd=/crowdsource/crowdsource-frontend)
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.23:npm (npm run package) @ crowdsource-frontend ---
[INFO] Running 'npm run package --color=false' in /crowdsource/crowdsource-frontend
[INFO] 
[INFO] > @ package /crowdsource/crowdsource-frontend
[INFO] > gulp
[INFO] 
[INFO] [18:11:09] Using gulpfile /crowdsource/crowdsource-frontend/gulpfile.js
[INFO] [18:11:09] Starting 'js-libs'...
[INFO] [18:11:09] Finished 'js-libs' after 19 ms
[INFO] [18:11:09] Starting 'js'...
[INFO] [18:11:09] Finished 'js' after 3.6 ms
[INFO] [18:11:09] Starting 'resources'...
[INFO] [18:11:09] Starting 'sass'...
[INFO] [18:11:10] Finished 'sass' after 1.25 s
[INFO] [18:11:11] Finished 'resources' after 1.9 s
[INFO] [18:11:11] Starting 'default'...
[INFO] [18:11:11] Finished 'default' after 5.66 μs
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.23:npm (javascript tests) @ crowdsource-frontend ---
[INFO] Running 'npm run test --color=false' in /crowdsource/crowdsource-frontend
[INFO] 
[INFO] > @ test /crowdsource/crowdsource-frontend
[INFO] > karma start src/test/javascript/karma.conf.js --single-run --browsers PhantomJS
[INFO] 
[INFO] INFO [karma]: Karma v0.12.37 server started at http://localhost:9876/
[INFO] INFO [launcher]: Starting browser PhantomJS
[INFO] INFO [PhantomJS 1.9.8 (Linux 0.0.0)]: Connected on socket L9PdPEWoqmDWDghoar6G with id 1169275
[INFO] WARN [web-server]: 404: /app/project/list/project-list.html
       DEBUG: 'Server error response as json:', '{"data":"NOT FOUND","status":404,"config":{"method":"GET","transformRequest":[null],"transformResponse":[],"cache":{},"url":"app/project/list/project-list.html","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":"Not Found"}', '; as object:', Object{data: 'NOT FOUND', status: 404, headers: function (name) { ... }, config: Object{method: 'GET', transformRequest: [...], transformResponse: [], paramSerializer: function ngParamSerializer(params) { ... }, cache: Object{put: ..., get: ..., remove: ..., removeAll: ..., destroy: ..., info: ...}, url: 'app/project/list/project-list.html', headers: Object{Accept: ..., Authorization: ...}}, statusText: 'Not Found'}
       ERROR: 'Error: [$compile:tpload] Failed to load template: app/project/list/project-list.html (HTTP status: 404 Not Found)
[INFO] http://errors.angularjs.org/1.4.8/$compile/tpload?p0=app%2Fproject%2Flist%2Fproject-list.html&p1=404&p2=Not%20Found
[INFO]     at handleError (http://localhost:9876/base/bower_components/angular/angular.js?7ff07aecce5af4039a1c32649be0ff2afcaebe47:17740)
[INFO]     at processQueue (http://localhost:9876/base/bower_components/angular/angular.js?7ff07aecce5af4039a1c32649be0ff2afcaebe47:14792)
[INFO]     at http://localhost:9876/base/bower_components/angular/angular.js?7ff07aecce5af4039a1c32649be0ff2afcaebe47:14808
[INFO]     at http://localhost:9876/base/bower_components/angular/angular.js?7ff07aecce5af4039a1c32649be0ff2afcaebe47:16052
[INFO]     at http://localhost:9876/base/bower_components/angular/angular.js?7ff07aecce5af4039a1c32649be0ff2afcaebe47:15870
[INFO]     at http://localhost:9876/base/bower_components/angular/angular.js?7ff07aecce5af4039a1c32649be0ff2afcaebe47:16160
[INFO]     at done (http://localhost:9876/base/bower_components/angular/angular.js?7ff07aecce5af4039a1c32649be0ff2afcaebe47:10589)
[INFO]     at completeRequest (http://localhost:9876/base/bower_components/angular/angular.js?7ff07aecce5af4039a1c32649be0ff2afcaebe47:10787)
[INFO]     at requestLoaded (http://localhost:9876/base/bower_components/angular/angular.js?7ff07aecce5af4039a1c32649be0ff2afcaebe47:10732)'
[INFO] PhantomJS 1.9.8 (Linux 0.0.0): Executed 36 of 242 SUCCESS (0 secs / 0.662 secs)
       PhantomJS 1.9.8 (Linux 0.0.0) financing rounds should send round data to backend and display it when valid data is submitted FAILED
[INFO] 	Error: Expected POST /financingrounds with different data
[INFO] 	EXPECTED: {"budget":320,"endDate":"2015-01-26T22:59:59.000Z"}
[INFO] 	GOT:      {"endDate":"2015-01-25T22:59:59.000Z","budget":320}
[INFO] 	    at $httpBackend (/crowdsource/crowdsource-frontend/bower_components/angular-mocks/angular-mocks.js:1212)
[INFO] 	    at sendReq (/crowdsource/crowdsource-frontend/bower_components/angular/angular.js:10559)
[INFO] 	    at /crowdsource/crowdsource-frontend/bower_components/angular/angular.js:10268
[INFO] 	    at processQueue (/crowdsource/crowdsource-frontend/bower_components/angular/angular.js:14792)
[INFO] 	    at /crowdsource/crowdsource-frontend/bower_components/angular/angular.js:14808
[INFO] 	    at /crowdsource/crowdsource-frontend/bower_components/angular/angular.js:16052
[INFO] 	    at /crowdsource/crowdsource-frontend/bower_components/angular/angular.js:15870
[INFO] 	    at /crowdsource/crowdsource-frontend/bower_components/angular/angular.js:16160
[INFO] 	    at /crowdsource/crowdsource-frontend/bower_components/angular/angular.js:23618
[INFO] 	    at /crowdsource/crowdsource-frontend/bower_components/jquery/dist/jquery.js:4435
[INFO] 	    at /crowdsource/crowdsource-frontend/bower_components/jquery/dist/jquery.js:4121
[INFO] 	    at /crowdsource/crowdsource-frontend/bower_components/jquery/dist/jquery.js:4350
[INFO] 	    at /crowdsource/crowdsource-frontend/bower_components/jquery/dist/jquery.js:4901
[INFO] 	    at /crowdsource/crowdsource-frontend/bower_components/jquery/dist/jquery.js:374
[INFO] 	    at /crowdsource/crowdsource-frontend/bower_components/jquery/dist/jquery.js:139
[INFO] 	    at /crowdsource/crowdsource-frontend/bower_components/jquery/dist/jquery.js:4902
[INFO] 	    at /crowdsource/crowdsource-frontend/bower_components/jquery/dist/jquery.js:7487
[INFO] 	    at /crowdsource/crowdsource-frontend/src/test/javascript/app/financing-rounds/financing-rounds.test.js:183
       PhantomJS 1.9.8 (Linux 0.0.0) financing rounds should display alert message when backend not responding on round start FAILED
[INFO] 	Error: Expected POST /financingrounds with different data
[INFO] 	EXPECTED: {"budget":320,"endDate":"2015-01-26T22:59:59.000Z"}
[INFO] 	GOT:      {"endDate":"2015-01-25T22:59:59.000Z","budget":320}
[INFO] 	    at $httpBackend (/crowdsource/crowdsource-frontend/bower_components/angular-mocks/angular-mocks.js:1212)
[INFO] 	    at sendReq (/crowdsource/crowdsource-frontend/bower_components/angular/angular.js:10559)
[INFO] 	    at /crowdsource/crowdsource-frontend/bower_components/angular/angular.js:10268
[INFO] 	    at processQueue (/crowdsource/crowdsource-frontend/bower_components/angular/angular.js:14792)
[INFO] 	    at /crowdsource/crowdsource-frontend/bower_components/angular/angular.js:14808
[INFO] 	    at /crowdsource/crowdsource-frontend/bower_components/angular/angular.js:16052
[INFO] 	    at /crowdsource/crowdsource-frontend/bower_components/angular/angular.js:15870
[INFO] 	    at /crowdsource/crowdsource-frontend/bower_components/angular/angular.js:16160
[INFO] 	    at /crowdsource/crowdsource-frontend/bower_components/angular/angular.js:23618
[INFO] 	    at /crowdsource/crowdsource-frontend/bower_components/jquery/dist/jquery.js:4435
[INFO] 	    at /crowdsource/crowdsource-frontend/bower_components/jquery/dist/jquery.js:4121
[INFO] 	    at /crowdsource/crowdsource-frontend/bower_components/jquery/dist/jquery.js:4350
[INFO] 	    at /crowdsource/crowdsource-frontend/bower_components/jquery/dist/jquery.js:4901
[INFO] 	    at /crowdsource/crowdsource-frontend/bower_components/jquery/dist/jquery.js:374
[INFO] 	    at /crowdsource/crowdsource-frontend/bower_components/jquery/dist/jquery.js:139
[INFO] 	    at /crowdsource/crowdsource-frontend/bower_components/jquery/dist/jquery.js:4902
[INFO] 	    at /crowdsource/crowdsource-frontend/bower_components/jquery/dist/jquery.js:7487
[INFO] 	    at /crowdsource/crowdsource-frontend/src/test/javascript/app/financing-rounds/financing-rounds.test.js:256
       PhantomJS 1.9.8 (Linux 0.0.0): Executed 242 of 242 (2 FAILED) (7.745 secs / -974587 mins 21.962 secs)
[ERROR] npm ERR! weird error 1
[ERROR] npm ERR! not ok code 0
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] crowdsource-parent ................................. SUCCESS [  0.218 s]
[INFO] crowdsource-frontend ............................... FAILURE [ 16.191 s]
[INFO] crowdsource-core ................................... SKIPPED
[INFO] crowdsource-example ................................ SKIPPED
[INFO] crowdsource-integrationtests ....................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16.717 s
[INFO] Finished at: 2016-11-28T18:11:21+08:00
[INFO] Final Memory: 20M/265M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.23:npm (javascript tests) on project crowdsource-frontend: Failed to run task: 'npm run test --color=false' failed. (error code 1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.23:npm (javascript tests) on project crowdsource-frontend: Failed to run task
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: Failed to run task
	at com.github.eirslett.maven.plugins.frontend.mojo.NpmMojo.execute(NpmMojo.java:62)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: com.github.eirslett.maven.plugins.frontend.lib.TaskRunnerException: 'npm run test --color=false' failed. (error code 1)
	at com.github.eirslett.maven.plugins.frontend.lib.NodeTaskExecutor.execute(NodeTaskExecutor.java:38)
	at com.github.eirslett.maven.plugins.frontend.mojo.NpmMojo.execute(NpmMojo.java:59)
	... 22 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :crowdsource-frontend

```

**Comment by wThomas84** [comment]
Hey Paul,

I am sorry for the inconvenience. 
It seems you found a bug (see #59 ) You also correctly found #10 which addresses the issue and will be refined.

For now you can do a dirty fix, that is to change the timezone on your machine to GMT.
On MacOs for example it works from the terminal:
`sudo systemsetup -settimezone GMT`
In order to see all timezeones available you can type:  `sudo systemsetup -listtimezones` 

Best regards
Tom

**Comment by Paul-Hoo** [comment]
Thank you for reply in time. I will try your way. Hope this bug can be fixed, and sorry I couldn't help since I don't know coding.
